config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'python-items', to: 'portfolios#python'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/share/_app_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</footer>

app/views/share/_app_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">TripTasker</h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</header>

app/views/share/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
</footer>

app/views/share/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h2 class="blog-title">Privacidad y Terminos de Uso</h2>
    <p class="lead blog-descriptio"></p>
    <%= link_to "Write a New Blog", new_blog_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/share/_blog_nav.html.erb
<div class="blog-masthead">
   <div class="container">
      <nav class="nav blog-nav">
        <%= nav_helper 'nav-link', 'span' %>
        <%= login_helper 'nav-link' %>
      </nav>
   </div>
</div>

app/views/share/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/JaoDev"><%= fa_icon "github" %></a></li>
      <li><a href="https://instagram.com/bogboni_official"><%= fa_icon "instagram" %></a></li>
      <li><a href="https://twitter.com/bogboni_"><%= fa_icon "twitter" %></a></li>
      <li><a href="https://facebook.com/bogboni"><%= fa_icon "facebook" %></a></li>
    </ol>
  </div>
</div><!-- /.blog-sidebar -->

app/views/share/_navbar.html.erb
<div class="<%= location %>">
  <%= link_to "Home", root_path %>
  <%= link_to "About", about_path %>
  <%= link_to "Contact", contact_path %>
  <%= link_to "Blog", blogs_path %>
  <%= link_to "Portfolio", portfolios_path %>
</div>

app/views/share/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View all portfolio items", portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/share/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
    <p>
      <%= link_to "About Us", about_path, class: 'btn btn-warning' %>
      <%= link_to "Blog Posts", blogs_path, class: 'btn btn-warning' %>
    </p>
  </div>
</section>

app/views/share/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Then, link them off to some social networking sites or contact information.</p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
  </div>
  <div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">TripTasker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <!-- <span class="navbar-toggler-icon"></span> -->
      <span class="line"></span>
      <span class="line"></span>
      <span class="line" style="margin-bottom: 0;"></span>
    </button>
  </div>
</div>